name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "branch1"] 
  pull_request:
    branches: [ "main", "branch1"]
  workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CashRegisterApp.sln

    - name: Build
      run: dotnet build CashRegisterApp.sln --no-restore

    - name: Test
      run: dotnet test CashRegisterApp.sln --no-build --verbosity normal

  build-and-push:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repo Name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}-api:latest
            ghcr.io/${{ env.REPO }}-api:${{ github.sha }}


      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}-web:latest
            ghcr.io/${{ env.REPO }}-web:${{ github.sha }}